import { NextResponse } from "next/server";

export async function GET() {
  const sampleMovies = [
    {
      id: 1,
      title: "Cocktail 2",
      poster: "https://images.unsplash.com/photo-1542204172-e7052809f852?q=80&w=600",
      year: 2026,
      genre: ["Drama", "Comedy", "Romance"],
      rating: 8.4,
      duration: "2h 14m",
      description: "An emotionally charged drama navigating contemporary urban love, friendships, and laughter.",
    },
    {
      id: 2,
      title: "Detective Conan: The Phantom Code",
      poster: "https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=600",
      year: 2026,
      genre: ["Anime & Animation", "Mystery and thrillers", "Crime & Suspense"],
      rating: 8.9,
      duration: "1h 50m",
      description: "A mastermind hacker leaves cryptic clues throughout Tokyo's neural network, challenging Conan to an intellectual duel.",
    },
    {
      id: 3,
      title: "Operation Safed Sagar",
      poster: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=600",
      year: 2026,
      genre: ["Action and adventure", "Crime & Suspense", "Drama"],
      rating: 8.7,
      duration: "2h 28m",
      description: "An elite special forces squadron executes an impossible high-altitude extraction deep behind hostile territory.",
    },
    {
      id: 4,
      title: "Cyberpunk Alley",
      poster: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=600",
      year: 2026,
      genre: ["Science fiction", "Action and adventure"],
      rating: 8.1,
      duration: "2h 10m",
      description: "In a neon-drenched metropolis, an AI investigator uncovers a syndicate rebellion threatening humanity's consciousness.",
    },
    {
      id: 5,
      title: "Lock Upp",
      poster: "https://images.unsplash.com/photo-1505635552518-3448ff116af3?q=80&w=600",
      year: 2025,
      genre: ["Horror", "Mystery and thrillers"],
      rating: 7.9,
      duration: "1h 42m",
      description: "In an abandoned mountain asylum, locked rooms unlock forgotten paranormal secrets that refuse to stay buried.",
    },
    {
      id: 6,
      title: "Musafir Cafe",
      poster: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=600",
      year: 2025,
      genre: ["Drama", "Romance", "Action and adventure"],
      rating: 8.3,
      duration: "2h 05m",
      description: "Two strangers meet on a high-altitude train journey, finding warmth and romance across breathtaking landscapes.",
    },
    {
      id: 7,
      title: "Magic Spell",
      poster: "https://images.unsplash.com/photo-1496345875659-11f7dd282d1d?q=80&w=600",
      year: 2025,
      genre: ["Fantasy", "Kids", "Action and adventure"],
      rating: 8.5,
      duration: "1h 55m",
      description: "A young alchemist discovers an ancient grimoire that can rewrite the laws of gravity and awaken enchanted kingdoms.",
    },
    {
      id: 8,
      title: "Earth Legacy",
      poster: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=600",
      year: 2024,
      genre: ["Documentary"],
      rating: 9.1,
      duration: "1h 45m",
      description: "An awe-inspiring journey through the planet's untouched oceanic wonders and primordial ecosystems.",
    },
    {
      id: 9,
      title: "The Last House",
      poster: "https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?q=80&w=600",
      year: 2025,
      genre: ["Horror", "Mystery and thrillers"],
      rating: 7.6,
      duration: "1h 38m",
      description: "A secluded coastal estate harbors whispering shadows that awaken when midnight falls.",
    },
    {
      id: 10,
      title: "Action Waves",
      poster: "https://images.unsplash.com/photo-1501430654243-c934ccd2e1c0?q=80&w=600",
      year: 2025,
      genre: ["Action and adventure", "Comedy"],
      rating: 8.0,
      duration: "1h 52m",
      description: "High-octane stunt racers take over coastal circuits in an adrenaline-fueled championship.",
    },
  ];

  return NextResponse.json(sampleMovies);
}